apiVersion: skaffold/v3
kind: Config
metadata:
  name: cloudfleet-node

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: ghcr.io/yegortokmakov/nodetest
      sync:
        manual:
          - src: "pages/**/*.js"
            dest: /app/pages
          - src: "public/**/*"
            dest: /app/public
          - src: "styles/**/*.css"
            dest: /app/styles

deploy:
  kubectl: {}

manifests:
  kustomize:
    paths:
      - kubernetes/overlays/dev
    buildArgs:
      - --load-restrictor
      - LoadRestrictionsNone

profiles:
  - name: production
    manifests:
      kustomize:
        paths:
          - kubernetes/overlays/production
