apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudfleet-node
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {}
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "27017"
    spec:
      serviceAccountName: cloudfleet-node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels: {}
      containers:
        - name: cloudfleet-node
          image: ghcr.io/yegortokmakov/ghtoken_product_demo
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
            limits:
              cpu: 50m
              memory: 300Mi

      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
