apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudfleet-node
spec:
  selector:
    matchLabels: {}
  template:
    spec:
      containers:
        - name: nextjs-app
          image: ghcr.io/yegortokmakov/nodetest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 150m
              memory: 300Mi
      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
