apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: "cloudfleet-node"
  app.kubernetes.io/part-of: "control-plane"
  app.kubernetes.io/instance: "cloudfleet-node"
